------------------------------------
-- CREAR BASE DE DATOS 
-- ING JESUS ARMANDO VALETA DORIA
------------------------------------

CREATE DATABASE TECNIMOTOS;

USE TECNIMOTOS;
-- DROP DATABASE TECNIMOTOS
------------------------------------
-- ESTRUCTURA DE LA TABLA CLIENTES
------------------------------------
CREATE TABLE CLIENTES(
ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
NOMBRES VARCHAR(30),
NUM_CEDULA LONG,
TELEFONO LONG,
DIRECCION VARCHAR(20),
PRIMARY KEY (ID_CLIENTE)
)ENGINE=InnoDB;



-------------------------------------
-- ESTRUCTURA DE LA TABLA PRODUCTOS
-------------------------------------
CREATE TABLE PRODUCTOS(
CODIGO VARCHAR(20) NOT NULL,
DESCRIPCION_P VARCHAR(20) NOT NULL,
PRECIO_VENTA DOUBLE,
CANTIDAD INT,
PRIMARY KEY (CODIGO)
)ENGINE=InnoDB;


--------------------------------------
-- ESTRUCTURA DE LA TABLA COMPRAS
--------------------------------------
CREATE TABLE COMPRAS(
ID_COMPRA VARCHAR(20),
FECHA_COMPRA DATE,
VALOR_COMPRA DOUBLE,
PRIMARY KEY (ID_COMPRA)
)ENGINE=InnoDB;

-----------------------------------------
-- ESTRUCTURA DE LA TABLA DETALLES_VENTAS
-----------------------------------------
CREATE TABLE DETALLES_COMPRAS(
ID_COMPRA VARCHAR(20),
CODIGO VARCHAR(20),
CANTIDAD INT,
VALOR_UNITARIO DOUBLE,
DESCUENTO DOUBLE,
PRECIO_NETO FLOAT,
VALOR_ENTRADA DOUBLE,
VALOR_TOTAL DOUBLE
)ENGINE=InnoDB;


---------------------------------------
-- ESTRUCTURA DE LA TABLA VENTAS
---------------------------------------
CREATE TABLE VENTAS(
ID_VENTA VARCHAR(20),
ID_CLIENTE INT,
FECHA_VENTA DATE,
VALOR_VENTA DOUBLE,
TIPO_VENTA VARCHAR(10),
PRIMARY KEY (ID_VENTA)
)ENGINE=InnoDB;


------------------------------------------
-- ESTRUCTURA DE LA TABLA VENTAS_PRODUCTOS
------------------------------------------
CREATE TABLE DETALLES_VENTAS(
ID_VENTA VARCHAR(20),
CODIGO VARCHAR(20),
CANTIDAD INT,
PRECIO_UNITARIO DOUBLE,
TOTAL DOUBLE
)ENGINE=InnoDB;


------------------------------------------
-- ESTRUCTURA DE LA TABLA CUENTASPORCOBRAR
------------------------------------------
CREATE TABLE CREDITOS(
ID_CREDITO INT NOT NULL AUTO_INCREMENT,
ID_CLIENTE INT,
TOTAL_CUENTA DOUBLE,
PRIMARY KEY (ID_CREDITO)
)ENGINE=InnoDB;


CREATE TABLE DEUDAS(
ID_DEUDA INT NOT NULL AUTO_INCREMENT,
ID_CLIENTE INT,
FECHA_DEUDA DATE,
VALOR_DEUDA DOUBLE,
PRIMARY KEY (ID_DEUDA)
);

CREATE TABLE PAGOS(
ID_PAGOS INT NOT NULL AUTO_INCREMENT,
ID_CLIENTE INT,
FECHA_PAGO DATE,
VALOR_PAGO DOUBLE,
PRIMARY KEY (ID_PAGOS)
);



--------------------------------------------
-- ESTRUCTURA DE LA TABLA USUARIO
--------------------------------------------
CREATE TABLE USUARIO(
  ID_USUARIO int(11) NOT NULL AUTO_INCREMENT,
  NOMBRES VARCHAR(50) NOT NULL,
  USUARIO VARCHAR(50) NOT NULL,
  CONTRASEÑA VARCHAR(100) NOT NULL,
  ROL VARCHAR(30) NOT NULL,
  PRIMARY KEY (ID_USUARIO)
)ENGINE=InnoDB;

INSERT INTO usuario Value(1,'Jesus Armando Valeta Doria','admin','123456','Administrador');
INSERT INTO usuario Value(2,'Carlos Navarro Tapia','auxi','123456','Auxiliar');


---------------------------------------------
-- RELACIONES DE LA TABLA DETALLES_COMPRAS
---------------------------------------------
ALTER TABLE DETALLES_COMPRAS
ADD CONSTRAINT  DETALLES_COMPRAS_FK_1 FOREIGN KEY (ID_COMPRA) REFERENCES COMPRAS (ID_COMPRA)ON DELETE SET NULL ON UPDATE CASCADE,
ADD CONSTRAINT DETELLES_COMPRAS_FK_2 FOREIGN KEY (CODIGO) REFERENCES PRODUCTOS (CODIGO) ON DELETE SET NULL ON UPDATE CASCADE;


--------------------------------------------
-- RELACIONES DE LA TABLA VENTAS
--------------------------------------------
ALTER TABLE VENTAS
ADD CONSTRAINT VENTAS_FK_1 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE) ON DELETE SET NULL ON UPDATE CASCADE;

--------------------------------------------
-- RELACIONES DE LA TABLA DETALLES_VENTAS
--------------------------------------------
ALTER TABLE DETALLES_VENTAS
ADD CONSTRAINT  DETALLES_VENTAS_FK_1 FOREIGN KEY (ID_VENTA) REFERENCES VENTAS(ID_VENTA) ON DELETE SET NULL ON UPDATE CASCADE,
ADD CONSTRAINT DETALLES_VENTAS_FK_2 FOREIGN KEY (CODIGO) REFERENCES PRODUCTOS (CODIGO) ON DELETE SET NULL ON UPDATE CASCADE;

--------------------------------------------
-- RELACIONES DE LA TABLA CREDITOS
--------------------------------------------
ALTER TABLE CREDITOS
ADD CONSTRAINT CREDITOS_FK_1 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE) ON DELETE SET NULL ON UPDATE CASCADE;


ALTER TABLE DEUDAS
ADD CONSTRAINT DEUDAS_FK_2 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE) ON DELETE SET NULL ON UPDATE CASCADE;


ALTER TABLE PAGOS
ADD CONSTRAINT PAGOS_FK_2 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE) ON DELETE SET NULL ON UPDATE CASCADE;



DROP TRIGGER IF EXISTS `DESCONTAR_STOCK_VENTAS`;
DELIMITER //
CREATE TRIGGER `DESCONTAR_STOCK_VENTAS` AFTER INSERT ON `DETALLES_VENTAS`
 FOR EACH ROW BEGIN
 UPDATE PRODUCTOS SET CANTIDAD = CANTIDAD - NEW.CANTIDAD 
 WHERE PRODUCTOS.CODIGO = NEW.CODIGO;
END
//
DELIMITER;

DROP TRIGGER IF EXISTS `AUMENTAR_STOCK_COMPRAS`;
DELIMITER //
CREATE TRIGGER `AUMENTAR_STOCK_COMPRAS` AFTER INSERT ON `DETALLES_COMPRAS`
 FOR EACH ROW BEGIN
 UPDATE Productos SET cantidad = cantidad + NEW.cantidad
 WHERE productos.codigo = NEW.codigo;
END
//
DELIMITER;


DROP TRIGGER IF EXISTS `CONTROLAR_PRECIO_DE_COMPRAS`;
DELIMITER //
CREATE TRIGGER `CONTROLAR_PRECIO_DE_COMPRAS` BEFORE INSERT ON `DETALLES_COMPRAS`
 FOR EACH ROW BEGIN
 UPDATE PRODUCTOS SET  PRECIO_VENTA = NEW.PRECIO_NETO 
 WHERE PRODUCTOS.CODIGO = new.CODIGO;
END
//
DELIMITER;




DROP TRIGGER IF EXISTS `AUMENTA_DEUDA_CLIENTE`;
DELIMITER //
CREATE TRIGGER `AUMENTA_DEUDA_CLIENTE` AFTER INSERT ON `DEUDAS`
 FOR EACH ROW BEGIN
 UPDATE CREDITOS,CLIENTES SET TOTAL_CUENTA = TOTAL_CUENTA+NEW.VALOR_DEUDA
 WHERE creditos.ID_CLIENTE=new.ID_CLIENTE;
END
//


DROP TRIGGER IF EXISTS `DESCUENTA_DEUDA_CLIENTE`;
DELIMITER //
CREATE TRIGGER `DESCUENTA_DEUDA_CLIENTE` AFTER INSERT ON `PAGOS`
 FOR EACH ROW BEGIN
 UPDATE CREDITOS,CLIENTES SET TOTAL_CUENTA = TOTAL_CUENTA-NEW.VALOR_PAGO
 WHERE creditos.ID_CLIENTE=new.ID_CLIENTE;
END